name: Deploy to Production (GitHub Pages) and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-variables: # Renamed from check-secrets for clarity
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Repository Variables and Secrets
        run: |
          if [ -z "${{ vars.TC_PROJECT_ID }}" ]; then
            echo "Error: TC_PROJECT_ID repository variable is not set."
            echo "Add it in Settings > Secrets and variables > Actions > Variables."
            exit 1
          fi
          
          if [ -z "${{ secrets.TC_API_KEY }}" ]; then
            echo "Error: TC_API_KEY repository secret is not set."
            echo "Add it in Settings > Secrets and variables > Actions > Repository secrets (NOT Environment secrets)."
            exit 1
          fi
          
          echo "✅ All required repository variables and secrets are set!"

  build-deploy-and-test:
    needs: check-variables
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for github-pages-deploy-action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install Main Dependencies
        run: npm ci
        
      - name: Install QACopilot CLI
        run: npm install github:TCSoftInc/qa-copilot-ci

      - name: Build Application
        run: npm run build
        env:
          PUBLIC_URL: /react-auth-app
        
      - name: Disable Jekyll Processing for gh-pages
        run: touch build/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          
      - name: Run QACopilot Tests Against Production
        run: |
          npx qac \
            --build ${{ github.run_id }} \
            --app_url https://abhimanyug.github.io/qac-sample-project/ \
            --tc_project_id ${{ vars.TC_PROJECT_ID }} \
            --api_key ${{ secrets.TC_API_KEY }}
        env:
          NODE_ENV: test
